### ISSUE TITLE
GKBarGraph uses same name as an Apple private selector

### ISSUE THREAD

**Issue by michaelsprindzuikate** [michalkonturek/GraphKit#14]
When validating the ipa in Xcode 6, I receive a warning saying that the GKBarGraph class is using a method with the same name as an Apple private selector.

The method in question is - (NSInteger)numberOfBars;

If I refactor the name to something like numberOfGraphBar and revalidate, it passes.

This is new in Xcode 6/iOS8 SDK it looks like.

Michael

**Comment by box86rowh** [comment]
I had to refactor this to get my build to itunes connect

**Comment by michalkonturek** [comment]
I am sorry to hear that.

**Comment by box86rowh** [comment]
@michalkonturek no worries, just wanted you to know that the issue is valid.
